### ISSUE TITLE
Meower+ doesn't exist?

### ISSUE THREAD

**Issue by GhostedNotFound** [meower-media-co/Meower-Windows#5]
When clicking on Meower+, Edge says that there is no website with that [URL](https://plus.meower.org).

I'm not sure if this is a typo in the URL, or Meower+ doesn't actually exist.

**Comment by wgyt** [comment]
hey there, meower+ is currently dead, you should remove all links to plus.meower.org or make them point to the archives

**Comment by Bloctans** [comment]
meower+ is being removed in version 1.3.
